[build]
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/bienfaits-flottaison"
  to = "/flottaison-isolation-sensorielle"
  status = 301
  force = false

[[redirects]]
  from = "/offres-bien-etre"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/offres-bien-etre?offer=flottaison"
  to = "/flottaison-isolation-sensorielle"
  status = 301
  force = false

[[redirects]]
  from = "/offres-bien-etre?offer=massage"
  to = "/massage-nantes"
  status = 301
  force = false

[[redirects]]
  from = "/offres-bien-etre?offer=flottaison-massage"
  to = "/massage-flottaison"
  status = 301
  force = false

[[redirects]]
  from = "/offres-bien-etre?offer=produits-cosmetiques"
  to = "/cosmetiques"
  status = 301
  force = false
