[build]
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/bienfaits-flottaison"
  to = "https://www.neoden.fr/flottaison-isolation-sensorielle"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre"
  to = "https://www.neoden.fr/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre?offer=flottaison"
  to = "https://www.neoden.fr/flottaison-isolation-sensorielle"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre?offer=massage"
  to = "https://www.neoden.fr/massage-nantes"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre?offer=flottaison-massage"
  to = "https://www.neoden.fr/massage-flottaison"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre?offer=produits-cosmetiques"
  to = "https://www.neoden.fr/cosmetiques"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
