[build]
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/bienfaits-flottaison"
  to = "https://www.neoden.fr/flottaison-isolation-sensorielle"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre"
  to = "https://www.neoden.fr/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre"
  to = "https://www.neoden.fr/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/offres-bien-etre"
  to = "https://www.neoden.fr/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
