[build]
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/bienfaits-flottaison"
  to = "/flottaison-isolation-sensorielle"
  status = 301
  force = false

[[redirects]]
  from = "/offres-bien-etre"
  to = "/"
  status = 301
  force = false
